version: 2.1
jobs:
  just_build:
    parameters:
      BUILD_VERSION: 
        type: string
      BUILD_TYPE:
        type: string
    docker:
      - image: cimg/base:2023.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Just
          command: |
            sudo apt install just
      - run:
          name: Build Docker image
          command: |
            just build_${BUILD_TYPE} ${BUILD_VERSION}

workflows:
  build_images:
    jobs:
      - start_python:
          name: Build Python ?
          type: approval
      - just_build:
          name: Build Python << matrix.BUILD_VERSION >>
          requires:
            - Build Python ?
          matrix:
            parameters:
              BUILD_VERSION: ["3.12"]
              BUILD_TYPE: ["python"]

      - start_php_fpm:
          name: Build PHP FPM ?
          type: approval
      - just_build:
          name: Build PHP FPM << matrix.BUILD_VERSION >>
          requires:
            - Build PHP FPM ?
          matrix:
            parameters:
              BUILD_VERSION: ["8.3"]
              BUILD_TYPE: ["php_fpm"]

      - start_php_fpm_dev:
          name: Build PHP FPM dev ?
          type: approval
      - just_build:
          name: Build PHP FPM Dev << matrix.BUILD_VERSION >>
          requires:
            - Build PHP FPM dev ?
            - Build PHP FPM << matrix.BUILD_VERSION >>
          matrix:
            parameters:
              BUILD_VERSION: ["8.3"]
              BUILD_TYPE: ["dev"]

      - start_php_cli:
          name: Build PHP CLI ?
          type: approval
      - just_build:
          requires:
            - Build PHP CLI ?
          matrix:
            parameters:
              BUILD_VERSION: ["8.3"]
              BUILD_TYPE: ["cli"]
        
          