version: 2.1
jobs:
  just_build:
    parameters:
      BUILD_VERSION: 
        type: string
      BUILD_TYPE:
        type: string
    docker:
      - image: cimg/base:2023.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Just
          command: |
            wget -qO - 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
            echo "deb [arch=all,$(dpkg --print-architecture) signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
            sudo apt update
            sudo apt install just
      - run:
          name: Build Docker image
          command: |
            just build_<< parameters.BUILD_TYPE >> << parameters.BUILD_VERSION >>

workflows:
  build_images:
    jobs:
      - start_python:
          name: Build Python ?
          type: approval
      - just_build:
          name: Build Python << matrix.BUILD_VERSION >>
          requires:
            - Build Python ?
          matrix:
            parameters:
              BUILD_VERSION: ["3.12"]
              BUILD_TYPE: ["python"]

      - start_php_fpm:
          name: Build PHP FPM ?
          type: approval
      - just_build:
          name: Build PHP FPM << matrix.BUILD_VERSION >>
          requires:
            - Build PHP FPM ?
          matrix:
            parameters:
              BUILD_VERSION: ["8.3"]
              BUILD_TYPE: ["php_fpm"]

      - start_php_fpm_dev:
          name: Build PHP FPM dev ?
          type: approval
      - just_build:
          name: Build PHP FPM Dev << matrix.BUILD_VERSION >>
          requires:
            - Build PHP FPM dev ?
            - Build PHP FPM << matrix.BUILD_VERSION >>
          matrix:
            parameters:
              BUILD_VERSION: ["8.3"]
              BUILD_TYPE: ["dev"]

      - start_php_cli:
          name: Build PHP CLI ?
          type: approval
      - just_build:
          requires:
            - Build PHP CLI ?
          matrix:
            parameters:
              BUILD_VERSION: ["8.3"]
              BUILD_TYPE: ["cli"]
        
          