version: 2.1
jobs:
  just_build_and_push:
    parameters:
      BUILD_VERSION: 
        type: string
      BUILD_TYPE:
        type: string
    docker:
      - image: cimg/base:2023.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Just
          command: |
            wget -qO - 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
            echo "deb [arch=all,$(dpkg --print-architecture) signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
            sudo apt update
            sudo apt install just
      - run:
          name: Build Docker image
          command: |
            just build_<< parameters.BUILD_TYPE >> << parameters.BUILD_VERSION >>
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            just push_<< parameters.BUILD_TYPE >> << parameters.BUILD_VERSION >>

workflows:
  build_images:
    jobs:
      - start_postgres:
          name: Build & Push PostgreSQL ?
          type: approval
      - just_build_and_push:
          name: Build & Push PostgreSQL << matrix.BUILD_VERSION >>
          requires:
            -  Build & Push PostgreSQL ?
          matrix:
            parameters:
              BUILD_VERSION: ["16", "17"]
              BUILD_TYPE: ["postgresql"]

      - start_timescaledb:
          name: Build & Push TimescaleDB ?
          type: approval
      - just_build_and_push:
          name: Build & Push TimescaleDB << matrix.BUILD_VERSION >>
          requires:
            -  Build & Push TimescaleDB ?
          matrix:
            parameters:
              BUILD_VERSION: ["16", "17"]
              BUILD_TYPE: ["timescaledb"]

      - start_python:
          name: Build & Push Python ?
          type: approval
      - just_build_and_push:
          name: Build & Push Python << matrix.BUILD_VERSION >>
          requires:
            -  Build & Push Python ?
          matrix:
            parameters:
              BUILD_VERSION: ["3.11", "3.12"]
              BUILD_TYPE: ["python"]

      - start_node:
          name: Build & Push Node ?
          type: approval
      - just_build_and_push:
          name:  Build & Push Node << matrix.BUILD_VERSION >>
          requires:
            -  Build & Push Node ?
          matrix:
            parameters:
              BUILD_VERSION: ["18", "20"]
              BUILD_TYPE: ["node"]

      - start_php_fpm:
          name: Build & Push PHP FPM ?
          type: approval
      - just_build_and_push:
          name: Build & Push PHP FPM << matrix.BUILD_VERSION >>
          requires:
            - Build & Push PHP FPM ?
          matrix:
            parameters:
              BUILD_VERSION: ["8.1", "8.2", "8.3"]
              BUILD_TYPE: ["php_fpm"]

      - start_php_fpm_dev:
          name: Build & Push PHP FPM dev ?
          type: approval
      - just_build_and_push:
          name: Build & Push PHP FPM Dev << matrix.BUILD_VERSION >>
          requires:
            - Build & Push PHP FPM dev ?
            - Build & Push PHP FPM << matrix.BUILD_VERSION >>
          matrix:
            parameters:
              BUILD_VERSION: ["8.1", "8.2", "8.3"]
              BUILD_TYPE: ["php_dev"]

      - start_php_cli:
          name: Build & Push PHP CLI ?
          type: approval
      - just_build_and_push:
          name: Build & Push PHP Cli << matrix.BUILD_VERSION >>
          requires:
            - Build & Push PHP CLI ?
          matrix:
            parameters:
              BUILD_VERSION: ["8.1", "8.2", "8.3"]
              BUILD_TYPE: ["php_cli"]
        
          